version: '3.8'

services:
  db:
    image: postgres:15
    container_name: warehouse_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: warehouse_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/warehouse_db
    ports:
      - "8000:8000"
    command: ["/bin/bash", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000"]
    #command: ["/bin/bash", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000 && python setup_db.py"]

volumes:
  pgdata:
